version: '3'

services:
  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://mysql_db:3306 -timeout 20s docker-entrypoint.sh node index.js
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password      
      - MYSQL_DATABASE=nodedb
    ports:
      - "3306:3306"
    
  nginx:
      build: 
        context: ./nginx
        dockerfile: Dockerfile
      ports:
        - "8080:80"
      depends_on: 
        - mysql_db
        - app
    